"""empty message

Revision ID: 873c1303ce48
Revises: c0d6f8b08f6c
Create Date: 2022-02-24 09:50:43.757661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '873c1303ce48'
down_revision = 'c0d6f8b08f6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zoeking', sa.Column('zoek_datum', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zoeking', 'zoek_datum')
    # ### end Alembic commands ###
