"""empty message

Revision ID: 993096c717a7
Revises: 
Create Date: 2022-02-24 09:34:43.947371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '993096c717a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zaak',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naam', sa.String(length=100), nullable=False),
    sa.Column('bvh', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('naam')
    )
    op.create_table('zoeking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naam', sa.String(length=100), nullable=False),
    sa.Column('zoek_patroon', sa.String(length=100), nullable=False),
    sa.Column('zaak_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['zaak_id'], ['zaak.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('naam'),
    sa.UniqueConstraint('zoek_patroon')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zoeking')
    op.drop_table('zaak')
    # ### end Alembic commands ###
