"""initial

Revision ID: a4d6a16ed10e
Revises: 
Create Date: 2022-02-23 21:20:01.085528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4d6a16ed10e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zaak',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naam', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('naam')
    )
    op.create_table('zoeking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naam', sa.String(length=100), nullable=False),
    sa.Column('zaak_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['zaak_id'], ['zaak.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('naam')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zoeking')
    op.drop_table('zaak')
    # ### end Alembic commands ###
